export const DEFAULT_PREFERENCES = {
  theme_mode: "dark",
  accent_color: "#89b4fa",
  accent_secondary: "",
  background_mode: "default",
  background_color: "#0b0e18",
  background_image_url: "",
  layout_mode: "standard",
  density: "comfortable",
  card_shape: "soft",
  font_scale: "normal",
  motion: "standard",
  operator_layout: "command",
  roster_layout: "cards",
  tab_style: "rail",
  surface_opacity: 0.92,
  surface_blur: 18,
  stream_card_style: "telemetry",
  dashboard_density: "command",
  profile_backdrop_image_url: "",
  profile_backdrop_strength: 0.18,
  sidebar_style: "full",
  panel_font_family: "system",
  card_hover_effect: "lift",
  notification_position: "br",
  bot_card_detail: "full",
  panel_radius: "medium",
  show_bot_uptime: true,
  show_queue_pressure: true,
  compact_sidebar: false,
};

export const CONTROL_ACTIONS = [
  "PLAY",
  "SMART_RECOMMEND",
  "PAUSE",
  "RESUME",
  "SKIP",
  "STOP",
  "CLEAR",
  "SHUFFLE",
  "LOOP",
  "FILTER",
  "LEAVE",
  "SET_HOME",
  "RECOVER",
  "RESTART",
];
