export const DEFAULT_PREFERENCES = {
  theme_mode: "dark",
  accent_color: "#89b4fa",
  background_mode: "default",
  background_color: "#0b0e18",
  background_image_url: "",
  layout_mode: "standard",
  density: "comfortable",
  card_shape: "soft",
  font_scale: "normal",
  motion: "standard",
  operator_layout: "command",
  roster_layout: "cards",
  tab_style: "rail",
  surface_opacity: 0.92,
  surface_blur: 18,
  stream_card_style: "telemetry",
  dashboard_density: "command",
};

export const CONTROL_ACTIONS = [
  "PLAY",
  "SMART_RECOMMEND",
  "PAUSE",
  "RESUME",
  "SKIP",
  "STOP",
  "CLEAR",
  "SHUFFLE",
  "LOOP",
  "FILTER",
  "LEAVE",
  "SET_HOME",
  "RECOVER",
  "RESTART",
];
